# Generated by Django 5.2.9 on 2025-12-03 23:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Part')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode Part')),
                ('category', models.CharField(choices=[('MAIN', 'Main Harness'), ('ENGINE', 'Engine Harness'), ('BODY', 'Body Harness'), ('DOOR', 'Door/Sensor Harness')], max_length=20, verbose_name='Kategori')),
                ('stock_qty', models.IntegerField(default=0, verbose_name='Stok Saat Ini')),
                ('min_stock_limit', models.IntegerField(default=100, verbose_name='Batas Buffer Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nama Mesin')),
                ('status', models.CharField(choices=[('RUNNING', 'Running Normal'), ('MAINTENANCE', 'Perbaikan Rutin'), ('BREAKDOWN', 'Rusak/Stop')], default='RUNNING', max_length=20)),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Pengecekan Terakhir')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Masuk dari Gudang'), ('OUT', 'Supply ke Housing/Produksi')], max_length=10, verbose_name='Tipe Transaksi')),
                ('quantity', models.IntegerField(verbose_name='Jumlah')),
                ('pic_name', models.CharField(max_length=100, verbose_name='PIC / Petugas')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.circuit', verbose_name='Sirkuit')),
            ],
        ),
    ]
